repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: check-toml
-   repo: local
    hooks:
    -   id: cargo-fmt
        name: cargo-fmt
        description: Format files with cargo fmt.
        entry: cargo fmt
        language: rust
        types: [rust]
        args: ["--"]
